# SPDX-FileCopyrightText: Copyright (C) 2026 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT

[files]
extend-exclude = [
  ".git/**",
  "target/**",
]

[default]
extend-ignore-re = [
  "[0-9a-f]{8,}"
]

